### ISSUE TITLE
JSON Decode error after migrating from plain text field

### ISSUE THREAD

**Issue by mijewe** [rynpsc/craft-phone-number#1]
Hi,

It's getting an invalid argument exception on "yii\helpers\BaseJson::decode('01234 123 123')"

I think what's happened is I've moved from a plain text field with "01234 123 123" set, and now that's not valid JSON so it's getting upset.

**Comment by rynpsc** [comment]
This will require some thought as we require both a region code and/or the number in international format e.g. +44. Ideally we'll take the existing value in this case "01234 123 123" and then try to convert it using the fields "Default Region", otherwise bail.

**Comment by rynpsc** [comment]
Just released 1.2.3 which will prevent the error in the interim whilst I work out a better way of converting existing strings into phone numbers.
