### ISSUE TITLE
Field doesn't save when creating/publishing new entry

### ISSUE THREAD

**Issue by omglolwtf** [rynpsc/craft-phone-number#12]
When creating a new entry, and inputting a phone number into a Phone Number field, when you click "publish entry", coming back to the entry edit page shows the Phone Number field is now blank. I have to input it a 2nd time for it to successfully save, it appears as if it'll only truly save the field until after the entry is "published".

PHP version 7.4.2
MySQL 5.7.26
Craft 3.6.10

Thanks :)!

**Comment by rynpsc** [comment]
Something has changed in Craft 3.6.10 which is causing the issue. I've opened an issue on Craft's end so will wait to see what they say. In the meantime if you are able to, downgrade to Craft 3.6.9 as the issue is not present in that version.

**Comment by rynpsc** [comment]
1.4.3 is now out with a fix for this. Thanks for reporting.
