### ISSUE TITLE
Link and format with single function

### ISSUE THREAD

**Issue by laurabennett** [rynpsc/craft-phone-number#14]
It would be great if you could pass the format string to getLink the same way you can to format().

So that I could write this
{{ entry.phone.getLink('national') }}
instead of this
<a href="{{ entry.phone.format('rfc3966') }}" title="click to call">{{ entry.phone.format('national') }}</a>

**Comment by rynpsc** [comment]
Thanks for the feature request. Have just released 1.5.0 that allows setting the content of the generated link.

In your case you can do:

```
{{ entry.phone.getLink({
  text: entry.phone.format('national')
}) }}
```

See the README for more info https://github.com/rynpsc/craft-phone-number#links

**Comment by estebancastro** [comment]
@rynpsc How can get the getRegionCode() and the format using text?

Silly example here, but I bet you got the point:

```
{{ entry.phone.getLink({
  text: entry.phone.getRegionCode().format('national')
}) }}
```

**Comment by rynpsc** [comment]
@estebancastro `format` can only be applied to the base model e.g `entry.phone.format('national')`. I'm not sure what your required output is but `text` can be any valid twig expression.

```twig
{{ entry.phone.getLink({
  text: entry.phone.getRegionCode() ~ entry.phone.format('national')
}) }}
```
