### ISSUE TITLE
Craft 4 500 error

### ISSUE THREAD

**Issue by robzor** [rynpsc/craft-phone-number#18]
Hi there, 

I've just installed your plugin but when I choose it as a field type I get a 500 error in the console and this error in the logs:

`2022-05-24 16:22:29 [web.ERROR] [Error] Error: Typed property rynpsc\phonenumber\fields\PhoneNumberField::$defaultRegion must not be accessed before initialization in /vendor/craftcms/cms/src/helpers/Template.php:90`

Craft CMS 4.0.3
Phone Number 2.0.0.1

**Comment by robzor** [comment]
I am not sure, but I think this fixes the issue:

line 30 of `vendor/rynpsc/craft-phone-number/src/fields/PhoneNumberField.php`:

`public ?string $defaultRegion = null;`

**Comment by rynpsc** [comment]
Thanks for reporting that. 2.0.1 is now out with a fix.

**Comment by robzor** [comment]
No problem, thanks for fixing it so quickly :)
