### ISSUE TITLE
Feed Me support

### ISSUE THREAD

**Issue by chrisrowe** [rynpsc/craft-phone-number#19]
I see from some other issues the field requires [region] and [number] child fields so I can see why feedme might not work but are you planning on supporting or do you know any work arounds?

**Comment by chrisrowe** [comment]
I worked around this by switching to a Plain Text field, importing text as `{"number":"800-430-6206 ext. 1325", "region":"US"}` then switching back to Phone, not ideal but did the job for now.

**Comment by rynpsc** [comment]
Version 2.2.0 is now out with built in support for Feed Me.

**Comment by chrisrowe** [comment]
TYSM! 🫶🏻

**Comment by funkysoul** [comment]
with latest craft 5 version and latest feedme, this isn't working at all
error: _Unable to find the template “feed-me/_includes/fields/_base.twig” in "phone-number/integrations/feedme/mapping-template" at line 40._
