### ISSUE TITLE
Incorrect Failed Area Code Validation

### ISSUE THREAD

**Issue by npruzaniec** [rynpsc/craft-phone-number#21]
Hello, thanks for the great plugin! I think I may have found a bug related to area codes.

Currently, it seems that `787` US phone numbers result in a validation error - though this is a valid US area code.

Let me know if you need any additional info.
![Screenshot 2024-02-06 at 10 50 21 AM](https://github.com/rynpsc/craft-phone-number/assets/1165220/7331807b-3035-42a9-b6d8-60c4b807791b)

**Comment by npruzaniec** [comment]
Plugin Version: `2.2.0`
Craft Version: `4.7.0`

**Comment by rynpsc** [comment]
Hi thanks for reporting an issue. The validation of phone numbers is handled by [libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php) which itself is a port of [libphonenumber](https://github.com/google/libphonenumber). I've checked the number against [libphonenumber](https://github.com/google/libphonenumber) and it's reporting it as invalid. If you think this is an error you would need to open an issue with [libphonenumber](https://github.com/google/libphonenumber) first and we can go from there, closing for now.

Here's the result from libphonenumber which is returning false for `isValidNumberForRegion()` 
https://libphonenumber.appspot.com/phonenumberparser?number=7878492590&country=US.

**Comment by npruzaniec** [comment]
Ok, thanks. I will take this up the chain!
