### ISSUE TITLE
Mapping error when using feedme

### ISSUE THREAD

**Issue by funkysoul** [rynpsc/craft-phone-number#22]
with latest craft 5 version and latest feedme, this isn't working at all
error: _Unable to find the template “feed-me/_includes/fields/_base.twig” in "phone-number/integrations/feedme/mapping-template" at line 40._

_Originally posted by @funkysoul in https://github.com/rynpsc/craft-phone-number/issues/19#issuecomment-2198200205_

**Comment by funkysoul** [comment]
nvm..

**Comment by laurabennett** [comment]
I am getting this error. Curious why you closed as completed. I reported to FeedMe that phone fields didn't work back in Craft 3 and then never fixed it :( Would be really nice if they worked together.  https://github.com/craftcms/feed-me/issues/600

**Comment by rynpsc** [comment]
This is fixed as of the general release of 3.0.
